### ISSUE TITLE
Error on page 13 of DaoFP PDF

### ISSUE THREAD

**Issue by davidainslie** [BartoszMilewski/Publications#10]
Should the following line under 3.2 Naturality:
Indeed, an arrow h probing b from x...

be changed to:
Indeed, an arrow h probing a from x...

**Comment by BartoszMilewski** [comment]
Yes, thank you! I'll fix it.

**Comment by tromp** [comment]
Page 31 appears to have a grammo in 

we’ll able to encode a hundred numbers

Btw, thanks for the fantastically educational writing!

**Comment by BartoszMilewski** [comment]
Done
