### ISSUE TITLE
Exercise 2.1.1 in DaoFP

### ISSUE THREAD

**Issue by bvoq** [BartoszMilewski/Publications#15]
Hello, great book!
I've gotten very confused with the exercise at 2.1.1:

<img width="792" alt="image" src="https://github.com/BartoszMilewski/Publications/assets/3169217/f44e6118-d29e-41a9-8b2d-715334624e8d">

Shouldn't the exercise instead be to prove? 
$((g \circ f) \circ -) = (g \circ (f \circ -))$

**Comment by BartoszMilewski** [comment]
This works too, but the idea is to prove something like, for instance, this:

import Data.Char

f :: Char -> Int
f = ord
g :: Int -> String
g = show

foo, bar :: (x -> Char) -> (x -> String)
foo = \h -> (g . f) . h
bar = (\j -> g . j) . (\h -> f . h)

test :: String -> Char
test = head . drop 1

main = do
  print $ (foo test) "abc"
  print $ (bar test) "abc"
