### ISSUE TITLE
Small mistake in "Monads and applicatives"

### ISSUE THREAD

**Issue by ncfavier** [BartoszMilewski/Publications#16]
> Since in a cartesian closed category every monad is lax monoidal

This is not true. A *strong* monad inherits a lax monoidal structure, and every monad on a self-enriched category is strong (as a previous section explains correctly), but this does not include all cartesian closed categories.

**Comment by BartoszMilewski** [comment]
But isn't every CC category canonically self-enriched?

**Comment by ncfavier** [comment]
Yes, sorry, that's not quite what I meant. Every *enriched* monad (that is $\mathcal{C}$-monad) on a monoidal closed category $\mathcal{C}$ is strong, but it is not the case that every monad on a self-enriched category is automatically enriched. I guess this is the sense in which Set is *canonically* self-enriched: when we say Set, we *mean* the Set-enriched category Set, and when we say "functor", we *mean* Set-enriched functor (this probably also illustrates why "canonical" should never be used).

As a counterexample, see [this MathOverflow answer](https://mathoverflow.net/a/85449/498826) (emphasis mine):

> So one example would be the monad on Cat (**considered as a Set-category**) whose algebras are cartesian closed categories -- it is known that this is not a Cat-monad (although it does extend to Cat as a groupoid-enriched category).

**Comment by ncfavier** [comment]
An easier example to wrap one's head around is example 3.1 in *Unicity of Enrichment over Cat or Gpd* by John Power. It's interesting to note that this example relies on Cat being the 1-category of *strict* categories though; it wouldn't work with univalent categories (but then Cat wouldn't be a 1-category to begin with).

**Comment by ncfavier** [comment]
This sentence on page 207 also needs fixing:

> For now, the magic incantation is that such a category is self-enriched, so every endofunctor is canonically enriched.

While I'm at it, typos on page 319:

> The generalization of a co-preshef is a V-funtor

and another instance of "funtor" on page 256.

**Comment by BartoszMilewski** [comment]
I'm considering adding a footnote: 
Again, the correct incantation is "every self-enriched monad"
I don't want to overwhelm the reader with too much information at this stage.

**Comment by ncfavier** [comment]
That seems wise (but it should be "every enriched monad", not "self-enriched")

**Comment by BartoszMilewski** [comment]
> This sentence on page 207 also needs fixing:
> 
> > For now, the magic incantation is that such a category is self-enriched, so every endofunctor is canonically enriched.
So what's a better way of saying that (without overwhelming the reader)?

**Comment by ncfavier** [comment]
Just remove the implication: "such a category is self-enriched, and we're working with enriched endofunctors"?

**Comment by BartoszMilewski** [comment]
In the latest revision I had: "For now, the magic incantation is that the category we're working with is self-enriched, and every endofunctor defined in Haskell is canonically enriched. " So I'll just remove "canonically".
