### ISSUE TITLE
Typesetting highlights should cover the space below the letters

### ISSUE THREAD

**Issue by clehene** [BartoszMilewski/Publications#17]
Hey - small nitpick for how the PDF is rendered. 
Note that when highlighting text, the space below the letters is not covered.

Dao of FP
![Dao FP](https://github.com/user-attachments/assets/6dbde502-f121-4193-b11e-1117db4f92a1)

CT in context
![CT in context](https://github.com/user-attachments/assets/b5e62430-2ad0-4dc3-a371-dc20c8c91da9)

**Comment by BartoszMilewski** [comment]
I wish I knew how to fix it. I'm using TeXShop to edit LaTeX and produce the PDFs.

**Comment by clehene** [comment]
Below this line is what GPT responded

-------------

When using TeXShop, which typically relies on `pdflatex` for PDF generation, the issue may be related to the specific LaTeX packages and commands you're using for highlighting. Here are more specific steps to ensure proper text highlighting in TeXShop:

### Using the `soul` Package for Highlighting

1. **Include the `soul` package**: Add this to the preamble of your LaTeX document.

    ```latex
    \usepackage{soul}
    \usepackage{xcolor}
    \sethlcolor{yellow}  % or any color you prefer
    ```

2. **Highlighting Text**: Use the `\hl` command provided by the `soul` package to highlight text.

    ```latex
    \hl{This text will be highlighted properly.}
    ```

### Example Document

Here’s a minimal working example that you can use in TeXShop to ensure proper highlighting:

```latex
\documentclass{article}
\usepackage{soul}
\usepackage{xcolor}
\sethlcolor{yellow}  % Set the highlight color

\begin{document}

This is normal text.

\hl{This text is highlighted and should appear correctly.}

\end{document}
```

### Troubleshooting

1. **PDF Viewer**: Ensure that you are using a PDF viewer that supports proper rendering of highlights. Some PDF viewers might not render the layered text and highlights correctly.

2. **TeXShop Preferences**: Ensure that TeXShop is set up to use `pdflatex` or another appropriate engine that supports the `soul` package correctly.

    - Go to `TeXShop` -> `Preferences`.
    - Under the `Typesetting` tab, ensure that `pdflatex` is selected as the default command.

3. **Check for Conflicts**: Ensure there are no conflicting packages or settings in your LaTeX document that might affect text rendering.

4. **Font and Encoding**: Sometimes, specific fonts or encoding settings can cause rendering issues. Ensure that your document uses standard fonts and encoding settings.

### Advanced Settings

If you still encounter issues, consider using `xelatex` or `lualatex`, which often provide better support for advanced text rendering features:

```latex
% For XeLaTeX
\documentclass{article}
\usepackage{soul}
\usepackage{xcolor}
\sethlcolor{yellow}

\begin{document}

This is normal text.

\hl{This text is highlighted and should appear correctly.}

\end{document}
```

In TeXShop, you can change the typesetting engine by selecting `XeLaTeX` from the drop-down menu before compiling the document.

### Summary

- **Use `soul` and `xcolor`** for proper text highlighting.
- **Ensure `pdflatex` or another appropriate engine** is used.
- **Check PDF viewer** compatibility.
- **Consider using `xelatex` or `lualatex`** for better text rendering support.

These steps should help you achieve the correct highlighting behavior in your LaTeX documents when using TeXShop.

**Comment by clehene** [comment]
I just realized that the tex files are online too (https://github.com/BartoszMilewski/DaoFP) so, perhap, this would be better directed there. With some building instructions, I'd be happy to try that out myself and report back.

**Comment by clehene** [comment]
Can't reproduce this locally. I suspect is something related to your build environment. 
Closing
