### ISSUE TITLE
Inadvertent pirate phraseology (Chapter 1. Page 4)

### ISSUE THREAD

**Issue by kitlangton** [BartoszMilewski/Publications#5]
From the top of Chapter 1's Page 4.

> Since we have assumed that **_there be no arrows_** from any other object to Void, there is no arrow from the terminal object to it

"There be no arrows" has a nice ring to it, however :)

**Comment by BartoszMilewski** [comment]
I'm using the subjunctive mood here. https://en.wikipedia.org/wiki/Subjunctive_mood

**Comment by kitlangton** [comment]
I be corrected 🙇
