### ISSUE TITLE
Buddies

### ISSUE THREAD

**Issue by davedawkins** [BartoszMilewski/Publications#6]
I'll come back to it and try again later , but I'm having a hard time seeing your intended meaning in the paragraph from Isomorphisms that talks about a buddy system, sending messages to each other, and no arrows being left behind. 

I think I'm following up to that point, I want credit for that.

**Comment by BartoszMilewski** [comment]
Are you familiar with one-to-one mappings? That's what I'm trying to explain. Each arrow in one set has its buddy in the other set.

**Comment by davedawkins** [comment]
OK, it was as simple as that 😳
